### ISSUE TITLE
Model.summary() failing due to irregular rich import

### ISSUE THREAD

**Issue by asingh9530** [keras-team/keras-core#463]
Hi team, 

Following error occurs while printing model.summary()
`module 'rich' has no attribute 'table'
`
This behaviour is reproducible in both mac os m2 silicon and windows intel x86, This could be eliminated using standard import structure while importing nested modules from packages like `from x import y` rather using non standard import structure `import x.y` 

Code to reproduce [Note - I am only able to reproduce it in mac and windows but not on collab which is linux based]

Solution -

Using following import 

```
from rich import table

from rich import markup

from rich import console
```

instead of `rich.table` or `rich.markup` or `rich.console`

@fchollet Since this is a small change, a small PR can rectify this.  Let me know if I can raise a PR to fix this.

Thanks

**Comment by fchollet** [comment]
This is fixed, you can pull up the latest version.

**Comment by asingh9530** [comment]
@fchollet I think still happening in mac and windows based os and I am able to reproduce it, also I can see in `main` branch there are still non-standard imports `import rich.table` rather `from rich import table`. 

This is the screenshot of the error
<img width="1031" alt="Screenshot 2023-07-13 at 7 55 55 AM" src="https://github.com/keras-team/keras-core/assets/16730377/4c40761d-ddfa-4511-98cb-27446853ef8c">

I think if possible we can change imports to following format  `from x import y`. Also in the previous [issue](https://github.com/keras-team/keras-core/issues/448), it was happening because `table` was not imported and this is due to non-standard import. 😅
